### ISSUE TITLE
Remove duplicated code in docker-compose.yml

### ISSUE THREAD

**Issue by riibeirogabriel** [learningOrchestra/learningOrchestra#73]
The docker-compose.yml has several parts of duplicated code, we need remove the dupicated code, this can help https://docs.docker.com/compose/compose-file/#extension-fields.

**Comment by riibeirogabriel** [comment]
@Nish251103

**Comment by Nish251103** [comment]
> @Nish251103

okay i would do the needful

**Comment by Nish251103** [comment]
done
