### ISSUE TITLE
Add hacktoberfest labels and topics to repo

### ISSUE THREAD

**Issue by navendu-pottekkat** [learningOrchestra/learningOrchestra#80]
As per the updated hacktoberfest rules, repos with hacktoberfest are only counted. Since we want to make our repo visible, we could add issues labelled hacktoberfest and mark PRs from now with hacktoberfest-accepted.

Check this doc for more info https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by riibeirogabriel** [comment]
Right, i will add a topic in this repo and get up issues with this label.

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat done.

**Comment by navendu-pottekkat** [comment]
@riibeirogabriel Nice, we will add hacktoberfest label to issues and hacktoberfest-accepted to PRs
