### ISSUE TITLE
Add all-contributors bot to recognize contributors

### ISSUE THREAD

**Issue by navendu-pottekkat** [learningOrchestra/learningOrchestra#81]
@riibeirogabriel Would you add all-contributors bot to this repo?

This is a good way to recognize all the contributors to this repo.

You can check here on how to do this: https://allcontributors.org/

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat it seems very good, i wiil see this after migrate the python client and docs, okay?

**Comment by navendu-pottekkat** [comment]
@riibeirogabriel sure!

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat i have intalled the bot in all repos.

**Comment by riibeirogabriel** [comment]
now we need call the bot?

**Comment by navendu-pottekkat** [comment]
yes, like this @all-contributors please add @navendu-pottekkat for doc and ideas

**Comment by navendu-pottekkat** [comment]
@riibeirogabriel Could you change the readme.md to README.md?

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat done

**Comment by navendu-pottekkat** [comment]
https://allcontributors.org/docs/en/emoji-key 

You can then use the emoji key to add contributions of the contributors. The bot will make a PR to the README automatically

**Comment by navendu-pottekkat** [comment]
Like this: https://github.com/nsfw-filter/nsfw-filter#contribute

**Comment by riibeirogabriel** [comment]
sounds good, @all-contributors please add @riibeirogabriel for code, infra, projectManagement, mentoring, maintenance

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat try again

**Comment by navendu-pottekkat** [comment]
You merge your PR and after that I will try again

**Comment by navendu-pottekkat** [comment]
@all-contributors please add @navendu-pottekkat for doc, design and ideas

**Comment by navendu-pottekkat** [comment]
Anytime someone makes a contribution we can immediately call the bot and credit them to encourage contributions

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat it sounds very good!

**Comment by riibeirogabriel** [comment]
But the bot crash the readme badges haha

**Comment by navendu-pottekkat** [comment]
> But the bot crashed the readme badges haha

That is because I used HTML format for the badges. It will be an easy fix. I will make PR
