### ISSUE TITLE
Move learningOrchestra to a GitHub organization

### ISSUE THREAD

**Issue by navendu-pottekkat** [learningOrchestra/learningOrchestra#82]
It would be easier to manage stuff in the future if everything is under one organisation.

Also keep two repos one for the the core code and the other for python-client.

You can transfer ownership without losing stars and stuff by creating a new user--> making user into an organisation --> transferring repo to that organisation

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat okay, i will see this now.

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat done, you can make a logo to organization profile like the header image created?

**Comment by navendu-pottekkat** [comment]
@riibeirogabriel Yes, I will do that. Meanwhile you can move the python-client to a different repo

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat yes, transfering now.

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat what repo name you suggest to create, i and my advisors planned create futures clients in java, javascript, etc to learningOrchestra, then i think a repo with /pythonClient name, what do you think?

**Comment by navendu-pottekkat** [comment]
yeah we could have this repo /learningOrchestra and the clients could be /learningOrchestra-python-client

The "-" is generally used in GitHub right?

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat right, i will make it.

**Comment by navendu-pottekkat** [comment]
@riibeirogabriel We can also move the docs to a separate page. Just to make things modular. 

I will try to design a web page too with the docs and a landing page.

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat yes, it will be amazing!
Do you want create other repo to docs?

**Comment by navendu-pottekkat** [comment]
right now you can move the docs folder to a separate repo and use gh-pages to host. I will then work on it. Should it be a landing page and repo or separate landing page and then a docs page ?

**Comment by riibeirogabriel** [comment]
Good, i will also copy the templates created by you, alright? I think which a separate landing page linking to docs-page could be a good idea, but you decide!

**Comment by navendu-pottekkat** [comment]
We can keep the docs as separate repo for now and we will see after we create the page

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat seems good

**Comment by navendu-pottekkat** [comment]
Have you thought of getting a domain name? If that is the case, we can have a primary domain and the subdomain like docs.website.com for hosting the docs and all. Anyway I will work on the front end of the landing page and docs

**Comment by riibeirogabriel** [comment]
We can get this, do you think a .com domain?

**Comment by navendu-pottekkat** [comment]
IDK what do you think? This is really useful for scaling this to a large audience. Maybe get something that is cheaper and also easily recognisable? Are there any other core contributors working on this? Let's ask what they think too

**Comment by riibeirogabriel** [comment]
I think .com domain a good choose, but searching seems not available, the learningOrchestra is a Monograph work in my Computer Science course, in next week i have a meet with my advisors and a possible new contributor to create a new feature in learningOrchestra, it will be a set of mircoservices to run a function/algorithm using distributed computing, it willl be builded using javascript. But i can ask them in this meet to know what they think.

**Comment by riibeirogabriel** [comment]
And i will keep developing the data scientist porpouse of learningOrchestra, there are too new requested features.

**Comment by riibeirogabriel** [comment]
I will create a set of issues to new contributors

**Comment by navendu-pottekkat** [comment]
@riibeirogabriel Ok, sounds cool. I will work on the docs and the landing page this week.

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat great! and thanks!

**Comment by navendu-pottekkat** [comment]
@riibeirogabriel Can I ask why the name learningOrchestra?

**Comment by riibeirogabriel** [comment]
Yes, learning is the machine learning purpouse, and the orchestra is by make a bit of services orchestration, but we will add deep learning microservices in next release and use new machine learning players, currently learningOrchestra uses the sparkML lib to make the machine learning model, but we want use sklearn, pytorch, open the set of possibilities.

**Comment by riibeirogabriel** [comment]
learningOrchestra was planned to treat BigData datasets, this explain the cluster environment and the spark uses.

**Comment by navendu-pottekkat** [comment]
Nice, Also maybe TensorFlow. I am a big fan of TensorFlow.

**Comment by riibeirogabriel** [comment]
TensorFlow also, it is a main player request by my data scientist advisor, i forget cite it, you will can contribute to learningOrchestra in next release of course if you wat.

**Comment by navendu-pottekkat** [comment]
> TensorFlow also, it is a main player request by my data scientist advisor, i forget cite it, you will can contribute to learningOrchestra in next release of course if you wat.

Of course, I will try to contribute

**Comment by riibeirogabriel** [comment]
You can suggest new features!!

**Comment by navendu-pottekkat** [comment]
@riibeirogabriel We can remove the python client from this repo right? Also moving the docs to another repo? I am currently working on the Python client readme docs

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat I will make this now, good!

**Comment by navendu-pottekkat** [comment]
@riibeirogabriel I have made the logo but I cannot add it since I am not admin of the organisation. How should I share it?

**Comment by riibeirogabriel** [comment]
How i add you how admin?

**Comment by navendu-pottekkat** [comment]
Maybe in the organisation settings?

**Comment by riibeirogabriel** [comment]
I am searching

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat done

**Comment by navendu-pottekkat** [comment]
@riibeirogabriel Made the changes. I have added some description also. We can improve in the future

**Comment by riibeirogabriel** [comment]
Good!

**Comment by riibeirogabriel** [comment]
@navendu-pottekkat I removed the python client and docs from this repo.
